import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const pyPath = path.join(root, "sniffer", "dofus_suite.py");
const targetTs = path.join(root, "api", "market", "suite-script.ts");

if (fs.existsSync(pyPath)) {
  const code = fs.readFileSync(pyPath, "utf-8");
  const content = `// Auto-generated by scripts/syncSuiteContent.js - DO NOT EDIT MANUALLY
export default function handler(req: any, res: any) {
  const scriptContent = ${JSON.stringify(code)};

  res.setHeader("Content-Type", "text/x-python; charset=utf-8");
  res.setHeader("Content-Disposition", 'attachment; filename="dofus_suite.py"');
  return res.status(200).send(scriptContent);
}
`;
  fs.writeFileSync(targetTs, content, "utf-8");
  console.log("✓ Synchronized api/market/suite-script.ts from sniffer/dofus_suite.py");
}
